dist: bionic

language: generic

install:

  # Install GNAT FSF and libfuse-dev 2.9
  - sudo apt-get -y install gnat gprbuild libxmlada-sax7-dev libfuse-dev

  # Install lcov for coverage
  - sudo apt-get -y install lcov

script:
  - ./configure --enable-coverage
  - make test
  - sh ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -f keystore.cov
